spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URL}
            authorization-grant-type: ${AUTH_GRANT_TYPE}
            scope: ${SCOPE}
            client-name: ${CLIENT_NAME}
        provider:
          naver:
            authorization-uri: ${AUTH_URL:https://nid.naver.com/oauth2.0/authorize}
            token-uri: ${TOKEN_URL:https://nid.naver.com/oauth2.0/token}
            user-info-uri: ${USER_INFO_URL:https://openapi.naver.com/v1/nid/me}
            user-name-attribute: ${RESPONSE:response}
            
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  jwt-secret: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  jwt-header: ${JWT_HEADER}
  jwt-prefix: ${JWT_PREFIX}

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000